### ISSUE TITLE
Error on production when using aws-sdk

### ISSUE THREAD

**Issue by jonathanmv** [MacKentoch/react-redux-bootstrap-webpack-starter#5] opened 2017-06-03 13:08 UTC
First of all, thank you very much for sharing this boilerplate. It's great

I just confirmed by cloning a fresh copy of this repo and only installing aws-sdk that `npm run serve-prod` will throw an error: *TypeError: Cannot set property 'createCredentials' of undefined*

I've been able to track it down to the crypo package (crypto-browserify@1.0.9) that aws-sdk uses as a dependency, but I haven't been able to solve it just yet.

I'm creating this issue so that other people know about this block and how to solve it (when solved...)

**Comment by MacKentoch** [comment] 2017-06-05 04:32
I'm sorry I don't know about aws-sdk.

**Comment by MacKentoch** [comment] 2017-06-13 11:29
Isn't it due to global variable?

Feel free to share your experience with AWS.

I never say no to new information

**Comment by jonathanmv** [comment] 2017-06-14 21:11
Not sure if it has something to do with a global variable.  I haven't tried to find what the issue is yet, I haven't taken the time to do it, sorry.

I'll share the solution if I find it, but to be honest I won't be working on it for now.

**Comment by MacKentoch** [comment] 2017-06-15 13:00
I stay tuned.

If I have to use AWS before (*not planned right now*) I will give a feedback.

**Comment by Enase** [comment] 2017-09-18 10:15
Hi guys,

I've had totally the same troble, so now I can share with u details.
So, the reason is [UglifyJsPlugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin). Try to disable the plugin or setup it in a way to skip/exclude aws skd.

**Comment by MacKentoch** [comment] 2017-09-18 10:53
@Enase thank you for taking time sharing.

**Comment by MacKentoch** [comment] 2017-09-18 13:32
By the way, does still occurred with latest version?

I remember I removed UglifyJs from webpack configs.

**Comment by cskeppstedt** [comment] 2017-09-21 11:47
Just wanted to say that I'm seeing this problem in our project (which is not related to react-redux-bootstrap-webpack-starter – we have a different webpack config all together). We're also seeing that the issue is solved by removing the UglifyJS plugin. Not uglifying the build is not really an option though, so we're trying to figure out a way to put all the AWS stuff in a separate bundle and then exclude that bundle from being uglified instead.

**Comment by MacKentoch** [comment] 2017-09-21 16:24
Thank you @cskeppstedt for sharing your experience 👍 +1

So I close this issue and I'm sorry not to have solutions to offer.

**Closed by MacKentoch** 2017-09-21 16:24 UTC

**Comment by ihle** [comment] 2017-10-09 09:26
For what it's worth, I managed to work around the issue by excluding variables called "exports" from the mangler, e.g. `mangle: { except: ['exports'] }`

**Comment by prateekro** [comment] 2017-12-29 09:10
@Enase What did you do to skip/exclude aws sdk to let go off this error?

**Comment by Enase** [comment] 2018-02-07 12:02
@prateekro Unfortunately I cannot reproduce the issue with the latest libraries, so that I cannot share or copy/paste the solution. Could you/someone share a code sample affected or steps to reproduce?

**Comment by janhoeck** [comment] 2018-02-20 08:59
I have to same problem in all my project, where I am using the UglifyPlugin and the aws-sdk.
After removing the aws-sdk, all works fine.
